### PR TITLE
Updates to support the latest Lasagne codebase

### PR DESCRIPTION
**Pull request by bluemellophone**
This is a fix for the current code to support the newest release of Lasagne.  This also supports a download script for the newer models of VGG-16 and VGG-19 and fixes for the conversion of these new files to Numpy arrays.

### CODE REVIEW

**Comment by 317070** [comment]
Did you manage to get a stream running?

**Comment by bluemellophone** [comment]
Sorry for the long delay.  

I have not tested the Twitch stream functionality, but I did try using the train_image.py code.  It seems to build, compile, and train correctly, which is nice.  I ran it for 1000 steps using the default settings and I see a log that looks like this:

```
Using gpu device 0: GeForce GTX TITAN X (CNMeM is enabled with initial size: 1.0% of memory, cuDNN 5105)
uint8
Usage: train_image.py <config_path>
Model: default_image
uint8
expid: default_image-Leviathan-20161027-111911
Building
  number of parameters: 138357544
  layer output shapes:
    InputLayer                       (1, 3, 1080, 1920)
    Conv2DDNNLayer                   (1, 64, 1080, 1920)
    Conv2DDNNLayer                   (1, 64, 1080, 1920)
    MaxPool2DDNNLayer                (1, 64, 540, 960)
    Conv2DDNNLayer                   (1, 128, 540, 960)
    Conv2DDNNLayer                   (1, 128, 540, 960)
    MaxPool2DDNNLayer                (1, 128, 270, 480)
    Conv2DDNNLayer                   (1, 256, 270, 480)
    Conv2DDNNLayer                   (1, 256, 270, 480)
    Conv2DDNNLayer                   (1, 256, 270, 480)
    MaxPool2DDNNLayer                (1, 256, 135, 240)
    Conv2DDNNLayer                   (1, 512, 135, 240)
    Conv2DDNNLayer                   (1, 512, 135, 240)
    Conv2DDNNLayer                   (1, 512, 135, 240)
    MaxPool2DDNNLayer                (1, 512, 67, 120)
    Conv2DDNNLayer                   (1, 512, 67, 120)
    Conv2DDNNLayer                   (1, 512, 67, 120)
    Conv2DDNNLayer                   (1, 512, 67, 120)
    MaxPool2DDNNLayer                (1, 512, 33, 60)
    Conv2DDNNLayer                   (1, 4096, 27, 54)
    Conv2DDNNLayer                   (1, 4096, 27, 54)
    Conv2DDNNLayer                   (1, 1000, 27, 54)
Compiling
image shape: (1, 3, 1080, 1920)
0 nan 23.4343 3471.6809082
1 nan 48.2266 3827.95654297
2 nan 63.5394 3728.69580078
3 nan 79.242 3553.12084961
4 nan 99.035 3448.47436523
5 nan 118.28 3325.44458008
6 nan 138.501 3280.46582031
7 nan 159.33 3185.74707031
8 nan 178.444 3143.81225586
9 nan 197.791 3073.94824219
10 nan 218.104 3035.65966797
...
990 nan 3450.36 2226.03417969
991 nan 3452.01 2336.80957031
992 nan 3458.18 2271.59863281
993 nan 3457.44 2319.12426758
994 nan 3454.13 2218.57495117
995 nan 3455.4 2330.49536133
996 nan 3462.84 2251.71386719
997 nan 3463.03 2330.51708984
998 nan 3462.23 2224.0859375
999 nan 3464.31 2342.50317383
1000 nan 3469.44 2263.28198242
```

The start image and the 1000-step resulting images are here: http://imgur.com/a/c009A.  You can see that running the code with the category "volcano" starts to give us volcano-y looking images.

**Comment by 317070** [comment]
I'm afraid something is off?
These were my results with train_image.py: http://317070.github.io/Dream/

I would say your results are 'underwhelming'?

**Comment by bluemellophone** [comment]
What seed image were you using for those images?  The same one I used?

**Comment by 317070** [comment]
I honestly have no idea. I guess so? The initial image has almost no influence on the result, however. (Or should not have influence). It is more like a seed for a random generator.
My guess, is that you have too much prior, or your neural network is not 100% functioning.

**Pull request closed without merging**
